### ISSUE TITLE
Obfuscation has changed

### ISSUE THREAD

**Issue by jeremehancock** [a-posadas/plugin.video.arconaitv#1]
Looks like they have changed their obfuscation. Any chance you are going to update your code? Really nice work here!

**Comment by a-posadas** [comment]
Thank you. I'll try to do it this weekend.

**Comment by a-posadas** [comment]
Since this weekend has come and gone, I may as well say that I have been looking into it and found these wonderful resources regarding the obfuscation. 

https://cat-in-136.github.io/2010/12/aadecode-decode-encoded-as-aaencode.html
https://github.com/mervick/php-aaencoder/blob/master/AADecoder.php
https://stackoverflow.com/questions/8883999/how-do-these-javascript-obfuscators-generate-actual-working-code

Personally, I have not been able to translate the decoder into python but someone has on php. I've managed to go through lines one through sixteen from the stackoverflow article, but line seventeen is where everything happens and that is a challenge for me. 

That's the best I've got as of right now. Hopefully someone will figure out a python way to deobfuscate aaencode and put it out there but for this application it's only a matter of months before they change their code again.

**Comment by a-posadas** [comment]
Ok, I think I did it. Can you please tell me if it is working or not.

**Comment by a-posadas** [comment]
Ok I had to redo the deobfuscation because it used a dangerous eval function. But it's done now. Please let me know if it is working.

**Comment by a-posadas** [comment]
closing this issue.
